[2025-06-11T09:11:02.363+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-11T09:11:02.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.fetch_and_store_covid_data scheduled__2025-06-10T00:00:00+00:00 [queued]>
[2025-06-11T09:11:02.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.fetch_and_store_covid_data scheduled__2025-06-10T00:00:00+00:00 [queued]>
[2025-06-11T09:11:02.396+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-11T09:11:02.408+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_store_covid_data> on 2025-06-10 00:00:00+00:00
[2025-06-11T09:11:02.416+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-11T09:11:02.417+0000] {standard_task_runner.py:63} INFO - Started process 66 to run task
[2025-06-11T09:11:02.417+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'fetch_and_store_covid_data', 'scheduled__2025-06-10T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/ covid_pipeline.py', '--cfg-path', '/tmp/tmpuawf_zhk']
[2025-06-11T09:11:02.418+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask fetch_and_store_covid_data
[2025-06-11T09:11:02.469+0000] {task_command.py:426} INFO - Running <TaskInstance: covid_data_pipeline.fetch_and_store_covid_data scheduled__2025-06-10T00:00:00+00:00 [running]> on host da27caf1d70a
[2025-06-11T09:11:02.562+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_covid_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-10T00:00:00+00:00'
[2025-06-11T09:11:02.562+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-11T09:11:04.040+0000] {logging_mixin.py:188} INFO - Fetched data: {'cases': 704753890, 'deaths': 7010681, 'recovered': 675619811, 'timestamp': datetime.datetime(2025, 6, 11, 9, 11, 4, 40437)}
[2025-06-11T09:11:04.060+0000] {logging_mixin.py:188} INFO - âœ… Data inserted into PostgreSQL successfully.
[2025-06-11T09:11:04.063+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-11T09:11:04.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-11T09:11:04.082+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=covid_data_pipeline, task_id=fetch_and_store_covid_data, run_id=scheduled__2025-06-10T00:00:00+00:00, execution_date=20250610T000000, start_date=20250611T091102, end_date=20250611T091104
[2025-06-11T09:11:04.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-11T09:11:04.187+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-11T09:11:04.188+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
