[2025-06-11T06:35:59.380+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-11T06:35:59.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: even_odd_branching.branching manual__2025-06-11T06:35:57.414805+00:00 [queued]>
[2025-06-11T06:35:59.409+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: even_odd_branching.branching manual__2025-06-11T06:35:57.414805+00:00 [queued]>
[2025-06-11T06:35:59.410+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-11T06:35:59.423+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branching> on 2025-06-11 06:35:57.414805+00:00
[2025-06-11T06:35:59.433+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=947) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-11T06:35:59.434+0000] {standard_task_runner.py:63} INFO - Started process 949 to run task
[2025-06-11T06:35:59.435+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'even_odd_branching', 'branching', 'manual__2025-06-11T06:35:57.414805+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/even_odd_branching.py', '--cfg-path', '/tmp/tmp1wepf_am']
[2025-06-11T06:35:59.437+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask branching
[2025-06-11T06:35:59.479+0000] {task_command.py:426} INFO - Running <TaskInstance: even_odd_branching.branching manual__2025-06-11T06:35:57.414805+00:00 [running]> on host 84435f84cb56
[2025-06-11T06:35:59.567+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='even_odd_branching' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T06:35:57.414805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T06:35:57.414805+00:00'
[2025-06-11T06:35:59.568+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-11T06:35:59.569+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-06-11T06:35:59.569+0000] {python.py:237} INFO - Done. Returned value was: even_task
[2025-06-11T06:35:59.569+0000] {branch.py:36} INFO - Branch into even_task
[2025-06-11T06:35:59.569+0000] {skipmixin.py:178} INFO - Following branch even_task
[2025-06-11T06:35:59.585+0000] {skipmixin.py:246} INFO - Skipping tasks [('odd_task', -1)]
[2025-06-11T06:35:59.607+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-11T06:35:59.623+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=even_odd_branching, task_id=branching, run_id=manual__2025-06-11T06:35:57.414805+00:00, execution_date=20250611T063557, start_date=20250611T063559, end_date=20250611T063559
[2025-06-11T06:35:59.647+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-11T06:35:59.694+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-11T06:35:59.695+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
