[2025-06-12T05:49:34.742+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-12T05:49:34.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_pipeline.fetch_and_store_covid_data scheduled__2025-06-11T00:00:00+00:00 [queued]>
[2025-06-12T05:49:34.782+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_pipeline.fetch_and_store_covid_data scheduled__2025-06-11T00:00:00+00:00 [queued]>
[2025-06-12T05:49:34.782+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-12T05:49:34.798+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_and_store_covid_data> on 2025-06-11 00:00:00+00:00
[2025-06-12T05:49:34.806+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-12T05:49:34.807+0000] {standard_task_runner.py:63} INFO - Started process 66 to run task
[2025-06-12T05:49:34.807+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'covid_data_pipeline', 'fetch_and_store_covid_data', 'scheduled__2025-06-11T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/ covid_pipeline.py', '--cfg-path', '/tmp/tmps6nm31_w']
[2025-06-12T05:49:34.808+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask fetch_and_store_covid_data
[2025-06-12T05:49:34.857+0000] {task_command.py:426} INFO - Running <TaskInstance: covid_data_pipeline.fetch_and_store_covid_data scheduled__2025-06-11T00:00:00+00:00 [running]> on host 5837b1149325
[2025-06-12T05:49:34.961+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_store_covid_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-11T00:00:00+00:00'
[2025-06-12T05:49:34.961+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-12T05:49:36.288+0000] {fetch_and_store.py:19} INFO - Fetched data: {'cases': 704753890, 'deaths': 7010681, 'recovered': 675619811, 'timestamp': datetime.datetime(2025, 6, 12, 5, 49, 36, 288282)}
[2025-06-12T05:49:36.296+0000] {fetch_and_store.py:53} INFO - ⏭️ No new data. Latest record matches current data. Skipping insert.
[2025-06-12T05:49:36.299+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-12T05:49:36.300+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-12T05:49:36.312+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=covid_data_pipeline, task_id=fetch_and_store_covid_data, run_id=scheduled__2025-06-11T00:00:00+00:00, execution_date=20250611T000000, start_date=20250612T054934, end_date=20250612T054936
[2025-06-12T05:49:36.384+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-12T05:49:36.421+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-12T05:49:36.423+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
